version: '3.8'

services:
  confluence-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: confluence-agent
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - PROTOCOL=http
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - ./logs:/app/logs